name: Deploy

on:
  push:
    branches-ignore:
      - 'main'
      - '/HOTFIX-.*/'
jobs:
  build_and_deploy:
    uses: nmahapure/marvel-github-workflows/.github/workflows/maven-sonar-jdk11.yaml@main
    secrets: inherit
