name: Release

on:
  push:
    branches:
      - 'main'
      - 'HOTFIX-**'
jobs:
  build_and_release:
    uses: nmahapure/marvel-github-workflows/.github/workflows/maven-sonar-jdk11.yaml@main
    secrets: inherit
